title: Digital Terroir
description: Exploring the intersection of software, culture, and place.
email: jordan@digitalterroir.org
baseurl: ""
# url: "https://digitalterroir.org"
url: ""

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

timezone: America/New_York
permalink: "/:title/"
paginate: 20
paginate_path: "/page/:num/"
future: false
markdown: kramdown
destination: _site

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
